# Configuração para usar variáveis de ambiente no servidor
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Ajuda o Spring a "falar" o dialeto correto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Em produção, 'validate' é mais seguro que 'update'. 
# Ele verifica se as tabelas correspondem ao modelo, mas não as altera.
spring.jpa.hibernate.ddl-auto=validate